### ISSUE TITLE
OTP 18 deprecation warnings

### ISSUE THREAD

**Issue by stocks29** [camshaft/pkcs7.erl#1]
src/proper_sets.erl:39: Warning: type set/0 is deprecated and will be removed in OTP 18.0; use use sets:set/0 or preferably sets:set/1
src/proper_sets.erl:39: Warning: type set/0 is deprecated and will be removed in OTP 18.0; use use sets:set/0 or preferably sets:set/1
Compiled src/proper_sets.erl
src/proper_queue.erl:38: Warning: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1
src/proper_queue.erl:38: Warning: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1
rc/proper_gb_trees.erl:38: Warning: type gb_tree/0 is deprecated and will be removed in OTP 18.0; use use gb_trees:tree/0 or preferably gb_trees:tree/2
src/proper_gb_trees.erl:38: Warning: type gb_tree/0 is deprecated and will be removed in OTP 18.0; use use gb_trees:tree/0 or preferably gb_trees:tree/2
Compiled src/proper_gb_trees.erl
src/proper_gb_sets.erl:41: Warning: type gb_set/0 is deprecated and will be removed in OTP 18.0; use use gb_sets:set/0 or preferably gb_sets:set/1
src/proper_gb_sets.erl:41: Warning: type gb_set/0 is deprecated and will be removed in OTP 18.0; use use gb_sets:set/0 or preferably gb_sets:set/1
src/proper_typeserver.erl:235: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:263: Warning: type set/0 is deprecated and will be removed in OTP 18.0; use use sets:set/0 or preferably sets:set/1
src/proper_typeserver.erl:264: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:266: Warning: type set/0 is deprecated and will be removed in OTP 18.0; use use sets:set/0 or preferably sets:set/1
src/proper_typeserver.erl:267: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:269: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:270: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:271: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:272: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:283: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:1057: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:235: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:263: Warning: type set/0 is deprecated and will be removed in OTP 18.0; use use sets:set/0 or preferably sets:set/1
src/proper_typeserver.erl:264: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:266: Warning: type set/0 is deprecated and will be removed in OTP 18.0; use use sets:set/0 or preferably sets:set/1
src/proper_typeserver.erl:267: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:269: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:270: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:271: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:272: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:283: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_typeserver.erl:1057: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
Compiled src/proper_typeserver.erl
src/proper_dict.erl:42: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/proper_dict.erl:42: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
Compiled src/proper_dict.erl
src/proper_array.erl:39: Warning: type array/0 is deprecated and will be removed in OTP 18.0; use use array:array/0 or preferably array:array/1
src/proper_array.erl:39: Warning: type array/0 is deprecated and will be removed in OTP 18.0; use use array:array/0 or preferably array:array/1

**Comment by camshaft** [comment]
Yeah it looks like it's coming from proper, which is really just a test dependency. We can make a rebar.test.config instead

**Comment by camshaft** [comment]
i've moved the dependency to triq. should be fixed
